#!/bin/bash
LOCAL_USER=pedro
LOCAL_IMAGE=oru-dgx
LOCAL_TAG=latest

REMOTE_USER=pedrozudo
REMOTE_IMAGE=oru-dgx
REMOTE_TAG=torch-1.13.0


docker tag $LOCAL_USER/$LOCAL_IMAGE:$LOCAL_TAG $REMOTE_USER/$REMOTE_IMAGE:$REMOTE_TAG
docker push $REMOTE_USER/$REMOTE_IMAGE:$REMOTE_TAG
